### ISSUE TITLE
lng

### ISSUE THREAD

**Issue by sec13b** [youcannotseemeagain/ele#1]
no offense , can ele.cna have also the English variant.

thank you

**Comment by youcannotseemeagain** [comment]
Thank you for your suggestion. I will consider writing the English version of ele.cna when the project receives high traffic. 
This project is temporarily used as a backup of my code.

**Comment by sec13b** [comment]
i like your project , but google dont translate correctly 
`"PrintSpoofer提权，推荐使用，后面跟要运行的exe全路径", "PrintSpoofer提权，后面跟要运行的exe全路径\n\n 使用说明:pipePotato`

and is take you few mins.
thank you

**Comment by youcannotseemeagain** [comment]
The cna file is now updated. 
I corrected the description errors and annotated them in English, and removed the useless alias

**Comment by sec13b** [comment]
thank you a lot
